# SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
#
# SPDX-License-Identifier: MPL-2.0

- type: entity
  id: Site14BaseMob
  abstract: true
  components:
  - type: Viewcone
  - type: ViewconeOccludable
  - type: HoldToFace
  - type: Blinking
