<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <OutputPath>..\..\..\bin\Content.Shared\</OutputPath>
      <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="..\..\..\RobustToolbox\Imports\Shared.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\Content.Shared\Content.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>

  <Import Project="..\..\..\RobustToolbox\MSBuild\Robust.Properties.targets" />
  <Import Project="..\..\..\RobustToolbox\MSBuild\Robust.CompNetworkGenerator.targets" />
</Project>
