# SPDX-FileCopyrightText: 2026 Site-14 Contributors
#
# SPDX-License-Identifier: MPL-2.0
#
# Additional Use Restrictions apply:
# See /LICENSES/SITE14-ADDENDUM.md

- type: entity
  parent:
  - BaseMob
  - MobCombat
  id: SCPPlayableBase
  abstract: true
  save: false
  components:
  - type: Stamina
  - type: Damageable
    damageContainer: Biological
  - type: NoSlip
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
  - type: MobThresholds
    thresholds:
      0: Alive
      1999: Critical
      2000: Dead
  
  