- type: jobIcon
  parent: SCPJobIcon
  id: SCPJobIconLogistician
  icon:
    sprite: /Textures/Site14/Interface/job_icons.rsi
    state: log

- type: jobIcon
  parent: SCPJobIcon
  id: SCPJobIconLogisticsDirector
  icon:
    sprite: /Textures/Site14/Interface/job_icons.rsi
    state: qm
